# Generated by Django 4.2.2 on 2023-06-18 06:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher')], max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='files/avatar')),
                ('student_rkv_id', models.IntegerField(blank=True, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, max_length=8, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=6, null=True)),
                ('class_name', models.CharField(blank=True, choices=[('X', 'X'), ('IX', 'IX'), ('VIII', 'VIII'), ('VII', 'VII'), ('VI', 'VI'), ('V', 'V')], max_length=5, null=True)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(default='Muzaffarpur', max_length=50)),
                ('state_and_ut', models.CharField(choices=[('ANDHRA PRADESH', 'ANDHRA PRADESH'), ('ANDAMAN & NICOBAR ISLAND', 'ANDAMAN & NICOBAR ISLAND'), ('ARUNACHAL PRADESH', 'ARUNACHAL PRADESH'), ('ASSAM', 'ASSAM'), ('BIHAR', 'BIHAR'), ('CHANDIGARH', 'CHANDIGARH'), ('CHATTISGARH', 'CHATTISGARH'), ('DADRA & NAGAR HAVELI & DAMAN & DIU', 'DADRA & NAGAR HAVELI & DAMAN & DIU'), ('DELHI', 'DELHI'), ('GOA', 'GOA'), ('GUJARAT', 'GUJARAT'), ('HARYANA', 'HARYANA'), ('HIMACHAL PRADESH', 'HIMACHAL PRADESH'), ('JHARKHAND', 'JHARKHAND'), ('JAMMU & KASHMIR', 'JAMMU & KASHMIR'), ('KARNATAKA', 'KARNATAKA'), ('KERALA', 'KERALA'), ('LADAKH', 'LADAKH'), ('LAKSHADWEEP', 'LAKSHADWEEP'), ('MADHYA PRADESH', 'MADHYA PRADESH'), ('MAHARASHTRA', 'MAHARASHTRA'), ('MANIPUR', 'MANIPUR'), ('MEGHALAYA', 'MEGHALAYA'), ('MIZORAM', 'MIZORAM'), ('NAGALAND', 'NAGALAND'), ('ODISHA', 'ODISHA'), ('PUDUCHERRY', 'PUDUCHERRY'), ('PUNJAB', 'PUNJAB'), ('RAJASTHAN', 'RAJASTHAN'), ('SIKKIM', 'SIKKIM'), ('TAMIL NADU', 'TAMIL NADU'), ('TELANGANA', 'TELANGANA'), ('TRIPURA', 'TRIPURA'), ('UTTARAKHAND', 'UTTARAKHAND'), ('UTTAR PRADESH', 'UTTAR PRADESH'), ('WEST BENGAL', 'WEST BENGAL')], default='BIHAR', max_length=50)),
                ('country', models.CharField(default='India', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('student', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
